/**
 * Central catalog of part types. New modules: add a definition here; UI + sim use this as source of truth.
 * Pins use local space: origin at part center, x right, y down, units in px (scaled by canvas).
 */
export const GRID = 8;
export const PART_SCALE = 1;

export const CATEGORIES = [
    { id: "power", label: "Power" },
    { id: "passive", label: "Passives" },
    { id: "semicon", label: "Diodes & LEDs" },
    { id: "transistor", label: "Transistors" },
    { id: "io", label: "Loads & I/O" },
    { id: "probes", label: "Meters" },
    { id: "ic", label: "Linear ICs" },
];

const commonPins = (left, right) => [
    { id: "a", name: "1", x: -left, y: 0 },
    { id: "b", name: "2", x: right, y: 0 },
];

export const MODULES = [
    {
        typeId: "gnd",
        name: "GND",
        shortName: "GND",
        category: "power",
        w: 56,
        h: 32,
        color: "var(--c-gnd)",
        accent: "var(--c-gnd-line)",
        description: "Reference node (0 V). This net is used as the simulation ground — connect the negative rail here.",
        pins: [
            { id: "g", name: "G", x: 0, y: 0 },
        ],
        sim: { kind: "ground" },
    },
    {
        typeId: "vbat",
        name: "DC Source",
        shortName: "V",
        category: "power",
        w: 96,
        h: 44,
        color: "var(--c-power)",
        accent: "var(--c-power-line)",
        description: "Ideal DC source. Set voltage in the inspector. Positive to negative follows pin order.",
        pins: [
            { id: "p", name: "+", x: -48, y: 0 },
            { id: "n", name: "−", x: 48, y: 0 },
        ],
        sim: { kind: "vsource" },
        defaultProps: { v: 9 },
    },
    {
        typeId: "vreg5",
        name: "5V Reg (ideal)",
        shortName: "5V",
        category: "power",
        w: 88,
        h: 40,
        color: "var(--c-power)",
        accent: "var(--c-power-line)",
        description: "Simplified 5V rail: between OUT and GND it behaves as a 5V source. IN is currently decorative (tie to a battery in your head).",
        pins: [
            { id: "in", name: "IN", x: -44, y: 0 },
            { id: "g", name: "GND", x: 0, y: 0 },
            { id: "out", name: "5V", x: 44, y: 0 },
        ],
        sim: { kind: "vreg" },
    },
    {
        typeId: "res",
        name: "Resistor",
        shortName: "R",
        category: "passive",
        w: 100,
        h: 36,
        color: "var(--c-res)",
        accent: "var(--c-res-line)",
        description: "Linear resistor. Set resistance in Ω. Series + parallel with anything that looks like a net.",
        pins: commonPins(50, 50),
        sim: { kind: "resistor" },
        defaultProps: { r: 1000 },
    },
    {
        typeId: "cap",
        name: "Capacitor",
        shortName: "C",
        category: "passive",
        w: 80,
        h: 36,
        color: "var(--c-cap)",
        accent: "var(--c-cap-line)",
        description: "DC model: a very high resistance (quasi open). For AC/ transient behavior, future versions can switch models.",
        pins: commonPins(40, 40),
        sim: { kind: "cap" },
    },
    {
        typeId: "ind",
        name: "Inductor",
        shortName: "L",
        category: "passive",
        w: 96,
        h: 36,
        color: "var(--c-ind)",
        accent: "var(--c-ind-line)",
        description: "DC model: a tiny resistance (quasi short).",
        pins: commonPins(48, 48),
        sim: { kind: "ind" },
        defaultProps: { r: 0.01 },
    },
    {
        typeId: "pot",
        name: "Potentiometer",
        shortName: "POT",
        category: "passive",
        w: 100,
        h: 56,
        color: "var(--c-pot)",
        accent: "var(--c-pot-line)",
        description: "Three terminal divider. Taper=wiper position 0–1. Total resistance 1kΩ in the sim (simplify).",
        pins: [
            { id: "a", name: "A", x: -50, y: 0 },
            { id: "w", name: "W", x: 0, y: 24 },
            { id: "b", name: "B", x: 50, y: 0 },
        ],
        sim: { kind: "pot" },
        defaultProps: { t: 0.5, r: 1000 },
    },
    {
        typeId: "sw",
        name: "SPST switch",
        shortName: "SW",
        category: "passive",
        w: 72,
        h: 36,
        color: "var(--c-sw)",
        accent: "var(--c-sw-line)",
        description: "Closed = ~20 mΩ, open = gigaohm. Toggle in the inspector or double-click the part on canvas.",
        pins: commonPins(36, 36),
        sim: { kind: "switch" },
        defaultProps: { closed: true },
    },
    {
        typeId: "btn",
        name: "Push (NO)",
        shortName: "BTN",
        category: "passive",
        w: 72,
        h: 40,
        color: "var(--c-btn)",
        accent: "var(--c-btn-line)",
        description: "Normally open, closes while pressed. Hold the button in the inspector for testing.",
        pins: commonPins(36, 36),
        sim: { kind: "button" },
        defaultProps: { pressed: false },
    },
    {
        typeId: "led",
        name: "LED",
        shortName: "LED",
        category: "semicon",
        w: 64,
        h: 40,
        color: "var(--c-led)",
        accent: "var(--c-led-line)",
        description: "Linearized: ~120–220 Ω + brightness from branch current. Anode = pin A, cathode = pin B (flat side).",
        pins: [
            { id: "a", name: "A", x: -32, y: 0 },
            { id: "k", name: "K", x: 32, y: 0 },
        ],
        sim: { kind: "led" },
    },
    {
        typeId: "diode",
        name: "Diode (Si)",
        shortName: "D",
        category: "semicon",
        w: 64,
        h: 36,
        color: "var(--c-dio)",
        accent: "var(--c-dio-line)",
        description: "Simplified: series 0.7 V + small resistance. Polarity: anode to cathode in pin order (A, K).",
        pins: [
            { id: "a", name: "A", x: -32, y: 0 },
            { id: "k", name: "K", x: 32, y: 0 },
        ],
        sim: { kind: "diode" },
    },
    {
        typeId: "zener",
        name: "Zener (3.3V ref)",
        shortName: "VZ",
        category: "semicon",
        w: 64,
        h: 36,
        color: "var(--c-zen)",
        accent: "var(--c-zen-line)",
        description: "A crude 3.3V clamp model: piecewise for demo only.",
        pins: [
            { id: "a", name: "A", x: -32, y: 0 },
            { id: "k", name: "K", x: 32, y: 0 },
        ],
        sim: { kind: "zener" },
        defaultProps: { vz: 3.3 },
    },
    {
        typeId: "npn",
        name: "NPN 2N2222 (DC)",
        shortName: "NPN",
        category: "transistor",
        w: 80,
        h: 60,
        color: "var(--c-npn)",
        accent: "var(--c-npn-line)",
        description: "Very simplified DC: either high-R off or a small on-resistance collector–emitter when base bias is on. (Educational, not for RF.)",
        pins: [
            { id: "c", name: "C", x: 0, y: -30 },
            { id: "b", name: "B", x: -40, y: 20 },
            { id: "e", name: "E", x: 40, y: 20 },
        ],
        sim: { kind: "npn" },
        defaultProps: { on: false },
    },
    {
        typeId: "nmos",
        name: "NMOS (2N7000ish)",
        shortName: "M",
        category: "transistor",
        w: 80,
        h: 60,
        color: "var(--c-mos)",
        accent: "var(--c-mos-line)",
        description: "DC model: D–S is either a large off resistance or a small R_on when Vgs>VT (toggle in inspector for now).",
        pins: [
            { id: "d", name: "D", x: 0, y: -30 },
            { id: "g", name: "G", x: -40, y: 20 },
            { id: "s", name: "S", x: 40, y: 20 },
        ],
        sim: { kind: "nmos" },
        defaultProps: { on: false },
    },
    {
        typeId: "lamp",
        name: "Lamp (incand.)",
        shortName: "L",
        category: "io",
        w: 72,
        h: 44,
        color: "var(--c-lamp)",
        accent: "var(--c-lamp-line)",
        description: "Resistive load with a thermal-ish brightness curve in the readout (still linear MNA in the mesh).",
        pins: commonPins(36, 36),
        sim: { kind: "lamp" },
        defaultProps: { r: 12 },
    },
    {
        typeId: "buzzer",
        name: "Buzzer (R)",
        shortName: "BZ",
        category: "io",
        w: 72,
        h: 40,
        color: "var(--c-bz)",
        accent: "var(--c-bz-line)",
        description: "Modeled as 40 Ω. Future: add AC + frequency.",
        pins: commonPins(36, 36),
        sim: { kind: "resistor" },
        defaultProps: { r: 40 },
    },
    {
        typeId: "vprobe",
        name: "Volt tap",
        shortName: "V?",
        category: "probes",
        w: 56,
        h: 32,
        color: "var(--c-probe)",
        accent: "var(--c-probe-line)",
        description: "High‑impedance voltmeter: shows V vs GND. Requires GND in the same net you reference.",
        pins: [
            { id: "g", name: "⊥", x: -28, y: 0 },
            { id: "p", name: "tip", x: 28, y: 0 },
        ],
        sim: { kind: "vprobe" },
    },
    {
        typeId: "probe",
        name: "Ammeter (series)",
        shortName: "A",
        category: "probes",
        w: 64,
        h: 36,
        color: "var(--c-amm)",
        accent: "var(--c-amm-line)",
        description: "1 mΩ shunt. Displays series current. Put it in the branch of interest.",
        pins: [
            { id: "a", name: "in", x: -32, y: 0 },
            { id: "b", name: "out", x: 32, y: 0 },
        ],
        sim: { kind: "ammeter" },
    },
    {
        typeId: "opamp",
        name: "Op‑amp (ideal buffer)",
        shortName: "OA",
        category: "ic",
        w: 96,
        h: 68,
        color: "var(--c-ic)",
        accent: "var(--c-ic-line)",
        description: "DC: a unity buffer between +IN and OUT (no rail limits). Simplified — not a full macromodel.",
        pins: [
            { id: "n", name: "−", x: -48, y: 10 },
            { id: "p", name: "+", x: -48, y: -10 },
            { id: "o", name: "out", x: 48, y: 0 },
        ],
        sim: { kind: "opamp" },
    },
    {
        typeId: "comp",
        name: "Comparator (ideal)",
        shortName: "CMP",
        category: "ic",
        w: 96,
        h: 60,
        color: "var(--c-ic)",
        accent: "var(--c-ic-line)",
        description: "Simplified: 5V step at OUT vs IN− (single supply mental model in readout; DC mesh uses a 1 GΩ to ref).",
        pins: [
            { id: "n", name: "−", x: -48, y: 8 },
            { id: "p", name: "+", x: -48, y: -8 },
            { id: "o", name: "out", x: 48, y: 0 },
        ],
        sim: { kind: "comparator" },
    },
    {
        typeId: "ne555",
        name: "555 (placeholder)",
        shortName: "555",
        category: "ic",
        w: 104,
        h: 72,
        color: "var(--c-ic)",
        accent: "var(--c-ic-line)",
        description: "Outline only for now — not simulated in this DC build. Stow it on the sheet for block diagrams.",
        pins: [
            { id: "gnd", name: "GND", x: -52, y: 24 },
            { id: "trig", name: "TR", x: -52, y: 0 },
            { id: "out", name: "OUT", x: 52, y: 0 },
            { id: "rst", name: "RST", x: 52, y: 24 },
            { id: "ctrl", name: "CV", x: 0, y: -32 },
        ],
        sim: { kind: "none" },
    },
];

export const moduleById = /* @__PURE__ */ (() => {
    const m = new Map();
    for (const def of MODULES) m.set(def.typeId, def);
    return m;
})();

export function getModulesInCategory(categoryId) {
    return MODULES.filter((d) => d.category === categoryId);
}
